# Generated by Django 4.1.5 on 2024-05-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "WhatIsHumanDesign",
            "0002_layoutwhat_content_url_layoutwhat_img_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layoutwhat",
            options={"verbose_name": "簡介人類圖首頁", "verbose_name_plural": "簡介人類圖首頁"},
        ),
        migrations.CreateModel(
            name="YourBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="內容標題")),
                ("content", models.CharField(max_length=1000, verbose_name="標題內容")),
                ("imgs_url", models.URLField(blank=True, verbose_name="內容圖片")),
                (
                    "layout_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WhatIsHumanDesign.layoutwhat",
                    ),
                ),
            ],
            options={
                "verbose_name": "人類圖是你的使用說明書部分",
                "verbose_name_plural": "人類圖是你的使用說明書部分",
            },
        ),
    ]
