# Generated by Django 4.1.5 on 2024-05-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WhatIsHumanDesign", "0003_alter_layoutwhat_options_yourbooks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layoutwhat",
            options={
                "verbose_name": "簡介人類圖首頁 (各分頁的索引值)",
                "verbose_name_plural": "簡介人類圖首頁 (各分頁的索引值)",
            },
        ),
        migrations.AlterField(
            model_name="yourbooks",
            name="content",
            field=models.TextField(verbose_name="標題內容"),
        ),
        migrations.AlterField(
            model_name="yourbooks",
            name="layout_key",
            field=models.ForeignKey(
                default="人類圖是你的人生使用說明書",
                on_delete=django.db.models.deletion.CASCADE,
                to="WhatIsHumanDesign.layoutwhat",
            ),
        ),
    ]
