# Generated by Django 5.0.6 on 2024-05-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "WhatIsHumanDesign",
            "0004_alter_layoutwhat_options_alter_yourbooks_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yourbooks",
            options={
                "verbose_name": "人類圖是你的人生使用說明書部分(索引值1)",
                "verbose_name_plural": "人類圖是你的人生使用說明書部分(索引值1)",
            },
        ),
        migrations.CreateModel(
            name="YourType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="內容標題")),
                ("content", models.TextField(verbose_name="標題內容")),
                ("imgs_url", models.URLField(blank=True, verbose_name="內容圖片")),
                (
                    "layout_key",
                    models.ForeignKey(
                        default="人類圖是你的人生使用說明書",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WhatIsHumanDesign.layoutwhat",
                    ),
                ),
            ],
            options={
                "verbose_name": "類型 = 你的天職(索引值2)",
                "verbose_name_plural": "類型 = 你的天職(索引值2)",
            },
        ),
    ]
