# Generated by Django 5.0.6 on 2024-05-30 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WhatIsHumanDesign", "0005_alter_yourbooks_options_yourtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layoutwhat",
            name="content_url",
        ),
    ]
