# Generated by Django 4.1.5 on 2024-06-01 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WhatIsHumanDesign", "0008_humanfather_yourmin"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HumanFather",
            new_name="YourFather",
        ),
    ]
