# Generated by Django 4.1.5 on 2024-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="aboutJeorme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_title", models.CharField(max_length=30, verbose_name="關於標題")),
                ("about_year", models.IntegerField(default=2013, verbose_name="關於年分")),
                (
                    "about_content",
                    models.TextField(max_length=800, verbose_name="關於內容"),
                ),
            ],
        ),
    ]
