# Generated by Django 4.1.5 on 2024-05-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freeVideo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freevideos",
            name="video_img",
            field=models.URLField(
                default="https://www.google.com.tw/url?sa=i&url=https%3A%2F%2Fwww.soundofhope.org%2Fpost%2F278421%3Flang%3Db5&psig=AOvVaw0_XGf_qSapc66CW8u2_xMR&ust=1716697830144000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLj_-4D8p4YDFQAAAAAdAAAAABAP",
                max_length=300,
                verbose_name="影片圖片連結",
            ),
        ),
        migrations.AlterField(
            model_name="freevideos",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="影片發布日期"),
        ),
        migrations.AlterField(
            model_name="freevideos",
            name="video_description",
            field=models.TextField(max_length=300, verbose_name="影片敘述"),
        ),
        migrations.AlterField(
            model_name="freevideos",
            name="video_link",
            field=models.URLField(max_length=300, verbose_name="影片連結"),
        ),
        migrations.AlterField(
            model_name="freevideos",
            name="video_title",
            field=models.CharField(max_length=30, verbose_name="影片標題"),
        ),
    ]
