# Generated by Django 4.1.5 on 2024-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freeVideo", "0002_freevideos_video_img_alter_freevideos_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freevideos",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "免費音檔",
                "verbose_name_plural": "免費音檔",
            },
        ),
        migrations.AlterField(
            model_name="freevideos",
            name="video_img",
            field=models.URLField(blank=True, max_length=300, verbose_name="影片圖片連結"),
        ),
    ]
