# Generated by Django 4.1.5 on 2024-06-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcess_title", models.CharField(blank=True, max_length=50)),
                ("process_content", models.TextField(blank=True, max_length=800)),
                ("process_icon", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_title", models.CharField(blank=True, max_length=50)),
                ("service_content", models.TextField(blank=True, max_length=800)),
            ],
        ),
    ]
