# Generated by Django 5.0.6 on 2024-06-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homePage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingprocess",
            options={"verbose_name": "預約流程", "verbose_name_plural": "預約流程"},
        ),
        migrations.AlterModelOptions(
            name="serviceitems",
            options={"verbose_name": "服務項目", "verbose_name_plural": "服務項目"},
        ),
        migrations.AlterField(
            model_name="bookingprocess",
            name="porcess_title",
            field=models.CharField(blank=True, max_length=50, verbose_name="預約標題"),
        ),
        migrations.AlterField(
            model_name="bookingprocess",
            name="process_content",
            field=models.TextField(blank=True, max_length=800, verbose_name="預約內容"),
        ),
        migrations.AlterField(
            model_name="bookingprocess",
            name="process_icon",
            field=models.URLField(blank=True, verbose_name="預約圖示"),
        ),
        migrations.AlterField(
            model_name="serviceitems",
            name="service_content",
            field=models.TextField(blank=True, max_length=800, verbose_name="預約內容"),
        ),
        migrations.AlterField(
            model_name="serviceitems",
            name="service_title",
            field=models.CharField(blank=True, max_length=50, verbose_name="服務標題"),
        ),
    ]
