# Generated by Django 4.1.5 on 2024-06-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "回饋狀態",
                "verbose_name_plural": "回饋狀態",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="不願意透漏身份的人", max_length=10)),
                ("message", models.TextField(verbose_name="回饋內容")),
                ("del_pass", models.CharField(max_length=10, verbose_name="刪除的密碼")),
                ("pub_time", models.DateTimeField(auto_now=True, verbose_name="回饋日期")),
                ("enabled", models.BooleanField(default=False, verbose_name="是否可以回饋")),
                (
                    "mood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserBack.mood"
                    ),
                ),
            ],
            options={
                "verbose_name": "回饋內容",
                "verbose_name_plural": "回饋內容",
            },
        ),
    ]
