# Generated by Django 5.0.6 on 2024-06-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_slot", models.TimeField()),
                ("end_slot", models.TimeField()),
                ("slot_description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("booking_description", models.CharField(max_length=100)),
                ("is_booking", models.BooleanField(default=False)),
                (
                    "booking_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="AllBooking.timeslot",
                    ),
                ),
            ],
        ),
    ]
