# Generated by Django 5.0.6 on 2024-06-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookings",
            options={"verbose_name": "預約內容", "verbose_name_plural": "預約內容"},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"verbose_name": "預約時段", "verbose_name_plural": "預約時段"},
        ),
        migrations.AddField(
            model_name="bookings",
            name="Day",
            field=models.CharField(default="星期日", max_length=50, verbose_name="星期幾"),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="Date",
            field=models.DateField(verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_description",
            field=models.CharField(max_length=100, verbose_name="項目標題"),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="AllBooking.timeslot",
                verbose_name="所在時段",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="is_booking",
            field=models.BooleanField(default=False, verbose_name="是否已預約"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_slot",
            field=models.TimeField(verbose_name="結束時點"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="slot_description",
            field=models.CharField(max_length=100, verbose_name="時段描述"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_slot",
            field=models.TimeField(verbose_name="開始時點"),
        ),
    ]
