# Generated by Django 5.0.6 on 2024-06-28 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0003_alter_bookings_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="Day",
        ),
    ]
