# Generated by Django 5.0.6 on 2024-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0004_remove_bookings_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="Day_id",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=5,
            ),
        ),
    ]
