# Generated by Django 4.1.5 on 2024-06-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0005_bookings_day_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="Day_id",
            field=models.IntegerField(
                choices=[
                    (1, "星期一"),
                    (2, "星期二"),
                    (3, "星期三"),
                    (4, "星期四"),
                    (5, "星期五"),
                    (6, "星期六"),
                    (7, "星期日"),
                ]
            ),
        ),
    ]
