# Generated by Django 4.1.5 on 2024-06-30 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0006_alter_bookings_day_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="Date",
            new_name="date",
        ),
    ]
