# Generated by Django 4.1.5 on 2024-07-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0008_booking_delete_bookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="slot_id",
            field=models.IntegerField(
                choices=[
                    (1, "Id 1"),
                    (2, "Id 2"),
                    (3, "Id 3"),
                    (4, "Id 4"),
                    (5, "Id 5"),
                    (6, "Id 6"),
                    (7, "Id 7"),
                ],
                default=1,
            ),
        ),
    ]
