# Generated by Django 4.1.5 on 2024-07-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0009_timeslot_slot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="slot_id",
            field=models.IntegerField(
                choices=[(1, "Id 1"), (2, "Id 2"), (3, "Id 3"), (4, "Id 4")],
                default=1,
                verbose_name="時段代碼",
            ),
        ),
    ]
