# Generated by Django 4.1.5 on 2024-07-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AllBooking", "0010_alter_timeslot_slot_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="Date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="Day_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="day_id",
            field=models.IntegerField(
                choices=[
                    (0, "Id 1"),
                    (1, "Id 2"),
                    (2, "Id 3"),
                    (3, "Id 4"),
                    (4, "Id 5"),
                    (5, "Id 6"),
                    (6, "Id 7"),
                ],
                default=0,
            ),
        ),
    ]
