# Generated by Django 4.1.5 on 2024-08-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "AllBooking",
            "0013_remove_timeslot_end_slot_remove_timeslot_start_slot_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel")),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslot",
                to="AllBooking.timeslot",
                verbose_name="所在時段",
            ),
        ),
    ]
